### ISSUE TITLE
大哥能分享一下接口的源码嘛

### ISSUE THREAD

**Issue by codehub666** [libsgh/189-down#4]
默认接口响应太慢啦：https://api.noki.top/pan/cloud189/shareToDown
想借用源码自己搭建个接口重新调试！

**Comment by codehub666** [comment]
想要单独的接口，最好是php语言，不会GO

**Comment by libsgh** [comment]
- 源码参考PanIndex的，php我不懂，你可以自行实现
- 我单独抽离了分享api，不过由于没有精力维护就不开源了，需要授权才可以使用
  https://github.com/libsgh/189-down/releases/download/v1.3/189-share-api-v1.3-linux-amd64.tar.gz
