### ISSUE TITLE
划水。一星好评

### ISSUE THREAD

**Issue by hbqjren** [libsgh/189-down#6]
作者。你做了这个有没有测试过。解析下载速度真的是蜗牛。登陆下载能跑100多M/S，用了这个下载不到2M/S

**Comment by libsgh** [comment]
演示站点是用我自己的账号解析的，这个号是个普通号...你可以用自己的vip号，另外， 也不排除多人使用会导致下载限速。最好自己搭个自己用。

**Comment by libsgh** [comment]
跟你解释下原理：就是登录后 获取下载地址，和你官网操作是一样的。
